export const USER_SIGNIN_API = "USER_SIGNIN_API";

export const ADD_HISTORY = "ADD_HISTORY";

export const US_LOGIN = "US_LOGIN";

export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";

export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";
