export const GET_USER_BY_PROJECT_ID_SAGA = "GET_USER_BY_PROJECT_ID_SAGA";
export const GET_USER_BY_PROJECT_ID = "GET_USER_BY_PROJECT_ID";

export const GET_USER_API = "GET_USER_API";

export const SIGNUP_SAGA = "SIGNUP_SAGA";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SAGA = "EDIT_USER_SAGA";

export const DELETE_USER_SAGA = "DELETE_USER_SAGA";
